### PR TITLE
fix: publish all dist files

### PR DESCRIPTION
**Pull request by mattlewis92**

### CODE REVIEW

**Comment by Gbuomprisco** [comment]
Hey @mattlewis92,  just published v0.8.2 (under the beta tag) in case you want to try it

**Comment by Gbuomprisco** [comment]
I'll hopefully have time tomorrow and i'll publish under latest

**Comment by mattlewis92** [comment]
Awesome, thank you! Verified and confirmed that it all works great in our app, now onto ngx-chips 😄

**Comment by Gbuomprisco** [comment]
Thanks a lot :)

**Comment by Gbuomprisco** [comment]
Happy to add you/team as contributors if you use these libs a lot! I don't have enough free time to update it so any help is welcome

**Comment by mattlewis92** [comment]
Yeah sure, would be happy to help! 😄

**Pull request merged**
