### PR TITLE
Fix animations in IE11

### PR DESCRIPTION
**Pull request by yanik**
Hi, so it seems that animations don't work properly in IE11 and I just changed them so it would work and it seems to me that the animation are equivalent (be great to here some feedback on that).

Initially I've done this in order to use it in ngx-chips, so I would be greatful if you use it and also make a release of ngx-chips (in the meantime I'll just use it myself in a fork). I guess that would fix this issue: https://github.com/Gbuomprisco/ngx-chips/issues/787

Thanks for your work!

### CODE REVIEW

**Comment by iamwhitebox** [comment]
@Gbuomprisco is there any way we can get this merged? I have a huge project that relies on this and its absolutely critical this component works in Safari 11/IE 11

**Comment by Gbuomprisco** [comment]
Hi @iamwhitebox, the tests are failing for some reasons. I need to check if it's safe to merge, hopefully later this evening, and I'll publish a new version

**Comment by Gbuomprisco** [comment]
v 0.10.1 released

**Comment by iamwhitebox** [comment]
Thank you!!!

**Comment by yanik** [comment]
@Gbuomprisco Great thanks! Would it also be possible to make a new release of ngx-chips using this new release? That would fix https://github.com/Gbuomprisco/ngx-chips/issues/787

**Comment by Gbuomprisco** [comment]
Hi @yanik. I just released 1.9.3 for ngx-chips

**Pull request merged**
